### ISSUE TITLE
EmptyStackException when increasing concurrent users ~>10

### ISSUE THREAD

**Issue by milindaperera** [wso2-attic/product-integration-server#31]
Sample : 

@Path("/stocks")
@Source(interface="default")
@Api(tags = {
    "stock_info",
    "stock_update"
}, description = "Rest api for get stocks details", produces = MediaType.APPLICATION_JSON)
package com.sample;

constant endpoint stockEP = new EndPoint("http://localhost:8080/stockquote/all");
constant endpoint stockEP2 = new EndPoint("http://localhost:8080/stockquote/IBM");

@GET
@PUT
@POST
@Path("/getStocks")
resource passthrough(message m) {
    message response;
    message response2;
    response = invoke(endpointKey=stockEP, messageKey=m);
    response2 = invoke(endpointKey=stockEP2, messageKey=response);
    reply response2;
    //reply response;
}
# Error : 

[2016-10-24 11:35:48,350] ERROR {org.wso2.carbon.transport.http.netty.sender.channel.pool.ConnectionManager} - Cannot return channel to pool java.lang.NullPointerException
    at org.wso2.carbon.transport.http.netty.sender.channel.pool.ConnectionManager.returnChannel(ConnectionManager.java:233)
    at org.wso2.carbon.transport.http.netty.sender.WorkerPoolDispatchingTargetHandler.channelRead(WorkerPoolDispatchingTargetHandler.java:77)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
    at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:244)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
    at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:110)
    at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
    at java.lang.Thread.run(Thread.java:745)

[2016-10-24 11:35:48,395] ERROR {org.wso2.carbon.gateway.core.flow.FlowControllerMediateCallback} - Error while mediating from Callback java.util.EmptyStackException
    at java.util.Stack.peek(Stack.java:102)
    at org.wso2.carbon.gateway.core.util.VariableUtil.getMap(VariableUtil.java:256)
    at org.wso2.carbon.gateway.core.flow.AbstractMediator.setObjectToContext(AbstractMediator.java:146)
    at org.wso2.carbon.gateway.core.flow.FlowControllerMediateCallback.done(FlowControllerMediateCallback.java:62)
    at org.wso2.carbon.transport.http.netty.sender.WorkerPoolDispatchingTargetHandler$1.run(WorkerPoolDispatchingTargetHandler.java:58)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

....

[2016-10-24 11:35:48,504] ERROR {io.netty.util.ResourceLeakDetector} - LEAK: ByteBuf.release() was not called before it's garbage-collected. Enable advanced leak reporting to find out where the leak occurred. To enable advanced leak reporting, specify the JVM option '-Dio.netty.leakDetectionLevel=advanced' or call ResourceLeakDetector.setLevel() See http://netty.io/wiki/reference-counted-objects.html for more information.

**Comment by maheshika** [comment]
Closed, since the repo is deprecated.
